### ISSUE TITLE
A little help running the initial script for scraping: scrape_user.py

### ISSUE THREAD

**Issue by anoduck** [umitkaanusta/TIA#3]
Barely a novice programming python, and I am a little lost on how exactly the script is intended to be run. I opened up pycharm and attempted to add the variable then execute the script with the python console:

```
usr = User(some_user)
scrape_user(usr)
```
As you probably surmised this did not work in the least. Then I added the variable `user = "some_user", then attempted to execute the script and this did not work as well. Adding `user = User("some_user") failed as well. So, I am lost as to how exactly this is supposed to be run. A little help would be greatly appreciated.

**Comment by umitkaanusta** [comment]
Assuming that the error is about doing the scraping properly, the problem here is probably about the Twint package (and/or Twitter's own "alarms"). If so, you can execute the functions in scrape_user step by step. If a step does not work, wait 1-2 mins and re-run that step again until the desired output comes.

Can you post the error message if it's something else than what I said above

**Comment by anoduck** [comment]
After running `python3 scrape_user.py` I recieve:

```
Traceback (most recent call last):
  File "scrape_user.py", line 1, in <module>
    from tia.stalk import URL_ROOT
ModuleNotFoundError: No module named 'tia.stalk'
```

**Comment by umitkaanusta** [comment]
You need to download TIA with the instructions given in README, seems like you're trying to use the script without downloading TIA.

**Comment by anoduck** [comment]
No. I cloned the repository and use it as CWD. The README barely elaborates on how to run the script, which is why I opened the issue.
Let me walk you through my process.

1. Clone the repository  
   `git clone https://github.com/umitkaanusta/TIA`

2. Change directory into repository  
   `cd TIA`
   
3. Install required packages from pip  
   `pip install -r requirements.txt`
   
4. At this point I should be ready to run the script.  

5. Change directory into tia/stalk  
   `cd tia/stalk`
   
6. Open up `scrape_user.py` in text editor.  
   `micro scrape_user.py`

7. Instructions in the bottom of the file are as follows:  
   ``` How to use the script?
	   \# Create a user instance with the username, like uka = User("umitkaanusta")
	   \# Then scrape_user(uka)```
	   
8. (This is where the confusion begins.) I Add the following to the top of the file below the import statements.  
   `user = User("some_username")`
   `scrape_user(user)`
	   
9. Save and close out editor.  

10. Execute the `scrape_user.py` script.  
	`python3 scrape_user.py`
	
11. I receive the following error:  
<code>
  Traceback (most recent call last):
  File "scrape_user.py", line 1, in <module>
  from tia.stalk import URL_ROOT
  ModuleNotFoundError: No module named 'tia.stalk'
</code>

### conclusion

What am I doing wrong? Why is this not working?

**Comment by umitkaanusta** [comment]
Main issue: https://github.com/umitkaanusta/TIA/issues/4

**Comment by anoduck** [comment]
Thanks again!
