### ISSUE TITLE
How to run scrape_user.py?

### ISSUE THREAD

**Issue by anoduck** [umitkaanusta/TIA#4]
@umitkaanusta I cloned the repository and use it as CWD. The README barely elaborates on how to run the script, which is why I opened the issue. Let me walk you through my process.

1. Clone the repository  
   `git clone https://github.com/umitkaanusta/TIA`

2. Change directory into repository  
   `cd TIA`
   
3. Install required packages from pip  
   `pip install -r requirements.txt`
   
4. At this point I should be ready to run the script.  

5. Change directory into tia/stalk  
   `cd tia/stalk`
   
6. Open up `scrape_user.py` in text editor.  
   `micro scrape_user.py`

7. Instructions in the bottom of the file are as follows:  
   ``` How to use the script?
	   \# Create a user instance with the username, like uka = User("umitkaanusta")
	   \# Then scrape_user(uka)
 
8. (This is where the confusion begins.) I Add the following to the top of the file below the import statements.  
   `user = User("some_username")`
   `scrape_user(user)`
	   
9. Save and close out editor.  

10. Execute the `scrape_user.py` script.  
	`python3 scrape_user.py`
	
11. I receive the following error:  
<code>
  Traceback (most recent call last):
  File "scrape_user.py", line 1, in <module>
  from tia.stalk import URL_ROOT
  ModuleNotFoundError: No module named 'tia.stalk'
</code>

### conclusion

What am I doing wrong? Why is this not working?

Was this written in Windows by any chance?

_Originally posted by @anoduck in https://github.com/umitkaanusta/TIA/issues/3#issuecomment-656397459_

**Comment by umitkaanusta** [comment]
Now I checked the error, yes TIA was written in Windows. Windows editors add some hidden characters at those __init__.py files, which makes them incompatible with Linux. Thank you for addressing this issue, I'll add a warning in README and work on this compatibility issue later on.

**Comment by anoduck** [comment]
That makes sense now. I will try it out on a windows virtualized instance and see if I have better luck. It explains why the import statements had no effect. I don't have pycharm for Windows, but I will install VScode and try it there. 

Thanks for the help resolving the confusion.
